### ISSUE TITLE
Jets Ruby Serverless Framework

### ISSUE THREAD

**Issue by tongueroo** [equivalent/we_demand_serverless_ruby#11]
> RE: Hey! Do you know of any other solution? Please let me know by raising an issue

Creator of [Jets](http://rubyonjets.com/) here. Jets adds Ruby supports to AWS Lambda. Here are some links:

* [Introducing Jets: A Ruby Serverless Framework on AWS Lambda](https://blog.boltops.com/2018/08/18/introducing-jets-a-ruby-serverless-framework)
* [Toronto Serverless Presentation: Jets Framework on AWS Lambda](https://blog.boltops.com/2018/09/25/toronto-serverless-presentation-jets-framework-on-aws-lambda) Also presented at the AWS Summit in Toronto but there's no recording for that.
* [AWS Lambda Ruby Support at Native Speed with Jets](https://blog.boltops.com/2018/09/02/aws-lambda-ruby-support-at-native-speed-with-jets)

**Comment by equivalent** [comment]
Thank you for this comment, I'll look into Jets. Unfortunately I'm hammered with work so this may take few days before it appears on the web-page 

(still PR with the description of Jets on https://www.serverless-ruby.org/ is welcome if you are interested ;)  )

**Comment by tongueroo** [comment]
@equivalent Sure. Added Jets with description to the index page. PR #13  Feel free to edit it.

**Comment by equivalent** [comment]
ok merged, thank you for contributing :+1:
