### ISSUE TITLE
IBM Cloud functions (Openwhisk)

### ISSUE THREAD

**Issue by db0sch** [equivalent/we_demand_serverless_ruby#12]
Apache openwhisk now support Ruby natively
Medium post: https://medium.com/openwhisk/ruby-goes-serverless-apache-openwhisk-adds-native-support-for-ruby-7134faee14e

And IBM serveless solution, IBM Cloud Function is using OpenWhisk for its infrastructure.
IBM Cloud Function website: https://www.ibm.com/cloud/functions
IBM Cloud Function documentation (on how to create Ruby actions): https://console.bluemix.net/docs/openwhisk/openwhisk_actions.html#creating-ruby-actions

Seems to be the first major cloud provider to support ruby for functions

**Comment by equivalent** [comment]
Thank you for this comment, I'll look into this. Unfortunately I'm hammered with work so this may take few days before it appears on the web-page 

(still PR with this description on https://www.serverless-ruby.org/ is welcome if you are interested ;)  )
