### ISSUE TITLE
https://faastruby.io/

### ISSUE THREAD

**Issue by blairanderson** [equivalent/we_demand_serverless_ruby#15]
I found this pretty great attempt at faas in ruby!

https://faastruby.io/

The annoying part is that it’s a new app, and wrapper around AWS or whatever. 

Pretty darn cool

**Comment by equivalent** [comment]
hi @blairanderson 

thank you for suggestion, we already have FaastRuby mentioned in the *Existing FaaS providers and FaaS solutions for Ruby* section

that section was directly added by the author :)

**Comment by equivalent** [comment]
BTW @blairanderson   author of FaaStRuby is looking for some feedback in ticket https://github.com/equivalent/we_demand_serverless_ruby/issues/9  I think he would like to hear from you your experience ;)
