### ISSUE TITLE
Serverless / Lambda support for Ruby

### ISSUE THREAD

**Issue by kingdonb** [equivalent/we_demand_serverless_ruby#16]
https://aws.amazon.com/blogs/compute/announcing-ruby-support-for-aws-lambda/

Given today's announcement from AWS, should there be an update to the petition text?

Now that two of the "big three" are officially supporting Ruby functions, maybe Azure will follow suit?

**Comment by equivalent** [comment]
Oh - my - GOD ! O_O .... best X-mas ever.

Thank you for letting me know, updating the website now !

**Comment by equivalent** [comment]
Updated the website  but I will have to update the entire website to be more informative.

I would appreciate yours and everyone opinion on https://github.com/equivalent/we_demand_serverless_ruby/issues/17

closing this issue for now
