### ISSUE TITLE
Iron?

### ISSUE THREAD

**Issue by drsharp** [equivalent/we_demand_serverless_ruby#2]
I've used Iron.io for a long time as a serverless architecture to run Ruby. And I just saw this: http://open.iron.io/ which on their github repo includes Ruby examples (such as: https://github.com/iron-io/functions/tree/master/examples/hello).

Shouldn't you add this to the list? Or even call out that there are serverless FaaS options available for Ruby today at Iron?

**Comment by equivalent** [comment]
Hi, thank you for pointing this out. I'll create a new section "existing FaaS providers" and I'll add it to the list. 

I was not aware of this, Much appreciated

**Comment by drsharp** [comment]
You are welcome!

**Comment by equivalent** [comment]
@drsharp can you pls confirm if I understand correctly that the provider Iron.io scheme of pricing for FaaS is like a prepaid plan for computing  ? 

https://try.iron.io/pricing-worker-monthly/

So if I need just some hobby project I'll pay $4.99 even if used only ore request per month ? 

So it's not like AWS lambda - pay for what you use in 100ms ?

Thank you for clarification

**Comment by equivalent** [comment]
https://github.com/equivalent/we_demand_serverless_ruby/pull/3/files  based on a discussion with Dave from Iron.io customer support chat window :)

**Comment by drsharp** [comment]
@equivalent yes, it's a different price model... it's not a "per-cpu" model as much. They used to have a free playground account, but since they were acquired (see https://blog.iron.io/full-circle-iron-io/ ) they dropped that, which is a bummer. It's still a great platform and I continue to use them. 👍

**Comment by equivalent** [comment]
thank you for sharing that. I'll close this issue ticket now as I've added section about it to https://www.serverless-ruby.org/ If there's anything I've missed pls let me know (or PR) 

thx again
