### ISSUE TITLE
OpenFaaS

### ISSUE THREAD

**Issue by rorpage** [equivalent/we_demand_serverless_ruby#4]
Runs on Docker/Kubernetes

**Comment by equivalent** [comment]
thank you for pointing this out, I'll add a section on it later today

**Comment by alexellis** [comment]
OpenFaaS runs on Docker Swarm, Nomad or Kubernetes - it's as home on the cloud as it is on your laptop or a bare metal cluster.

We have a language template for Ruby so you can create Ruby functions easily including support for gems.. email alex@openfaas.com if you'd like to join the Slack community and find out more, or check out the workshop/tutorial - https://github.com/openfaas/workshop

**Comment by equivalent** [comment]
@alexellis @rorpage I've added section on OpenFaaS to https://www.serverless-ruby.org/

(once again thank you for pointing it out) 

Can you pls have a look if you want to add / change something ...or feel free to  PR if you like to (this file: https://github.com/equivalent/we_demand_serverless_ruby/blob/master/app/views/signatures/index.html.erb) 

Thx
